### PR TITLE
Allow test runs to complete despite errors

### PR DESCRIPTION
**Pull request by arscan**

### CODE REVIEW

**Comment by arscan** [comment]
@okeefm could you test to make sure that your auth failure case works as you expect before merging?  It should look something like this (I hardcoded the History Test to error out in this example):

screen shot 2015-10-29 at 4 03 28 pm

**Comment by okeefm** [comment]
I tried it on the secured and unsecured bonfire.mitre.org servers. Neither of them hard-failed, but I'm not sure if they were still error-ing.

**Comment by arscan** [comment]
Hrm... any chance you could checkout master and see if is still breaking for those servers & tests?

**Comment by okeefm** [comment]
It doesn't look like it is still breaking for those servers/tests.

**Comment by arscan** [comment]
That's too bad... in order to see it "work" then would be to raise an error inside TestRun#execute method, near where the test.execute function is run.

I did something like `raise "Some kind of error" if t.title == "HistoryTest"`, and make sure you run the history test test (among other tests).  Citing by memory so the var names might be slightly different, but you get the idea.

**Comment by okeefm** [comment]
Ok, I'll fake a test error to test this.

**Comment by okeefm** [comment]
Test this; it works for me with a faked error.

**Pull request merged**
