### PR TITLE
Front page performance

### PR DESCRIPTION
**Pull request by arscan**

### CODE REVIEW

**Comment by arscan** [comment]
FYI @kjmahalingam, these changes I made fixed the performance issues that we were seeing.  I just restricted the queries to only return the data that was being used on the page.  The front page is now showing many more servers than before, and all the servers now have a full 52 week summary history.  That was a lot of data for rails to pull from mongo, especially since we weren't using it.

**Comment by jawalonoski** [comment]
Still too slow.

**Comment by arscan** [comment]
@jawalonoski was this in regards to that history test run being slow or something else?  The front page may be faster than it has been in awhile actually.

**Comment by jawalonoski** [comment]
It may have been the venue network.

The history test isn't finished, and it hasn't "fixed itself."

**Comment by arscan** [comment]
Yeah I noticed that and am working on it.

**Comment by arscan** [comment]
All set -- the script that kicks stalled runs had a hard reference to the old version of ruby.

**Pull request merged**
