### PR TITLE
Edit server endpoint

### PR DESCRIPTION
**Pull request by Evana13G**

### CODE REVIEW

**Comment by Evana13G** [comment]
screen shot 2015-10-06 at 11 38 43 am

**Comment by Evana13G** [comment]
screen shot 2015-10-06 at 11 39 28 am

**Comment by arscan** [comment]
If you make changes to the server name or the URL, click save, then hover-over the URL or server if they are too long, the tooltip that comes up isn't changed.  This is a problem if you want to change the end of a long URL, then want to verify it has changed by hover-overing the url, it appears to have not saved even though it has.
screenshot

**Comment by arscan** [comment]
I think that this is out of the scope of this change, but just fyi, that lock icon apparently messes up some of the wrapping a bit.  See screenshots.  I will go ahead and commit this though.

screen shot 2015-10-13 at 11 10 23 am
screen shot 2015-10-13 at 11 11 27 am

**Pull request merged**
