### PR TITLE
Preemptively raise error if result size larger than approx 16mb.

### PR DESCRIPTION
**Pull request by arscan**

### CODE REVIEW

**Comment by jawalonoski** [comment]
Umm... is this what you want to do? Totally bomb out?

**Comment by okeefm** [comment]
To be fair, we are `rescue`-ing just below this, so it doesn't so much bomb out as trip the "this test errored" code.

**Comment by arscan** [comment]
This mimics what I would expect mongoid to do (but apparently it doesn't do), which is raise an error when you try to save a test result that is too large.  The runner will mark this suite as an error (and put in the error message into each test's message area), and continue to the next suite... which is better than mongoid completely crashing the job runner.  The alternatives are a bit messy, because that 16mb could be a combination of a whole bunch of big responses throughout the suite.   Let's discuss at our meeting.

**Comment by arscan** [comment]
Also, I"m not 100% convinced that this is what is causing our nightlies to die, but I'm having trouble hitting the servers with problems outside of our production environment, so I figured I'd start with this and then see if it improves stability.  Then we could circle back and add more sophisticated solutions, like replacing just the huge responses outright, or trying to gut out big parts of bundles.

**Pull request merged**
