### PR TITLE
Javascript testing

### PR DESCRIPTION
**Pull request by andrequina**
initial testing for javascript
##### Front end tests
- Install phantomjs: `brew install phantomjs`
- Install istanbul: `npm install -g istanbul`
- Execute: `bundle exec rake teaspoon`

### CODE REVIEW

**Comment by arscan** [comment]
Should this be included in travis @andrequina?  From what I can tell it is not being run there.

I could guess how this would included: add some lines in travis.yaml to install the appropriate test framework and then run teaspoon.  But it might be better for you to do it.

Besides this issue I was able to follow along and the coverage report is consistent with what I would expect it to be based on the tests you have put in.

**Comment by arscan** [comment]
This looks like about the most annoying thing to debug ever.

**Comment by andrequina** [comment]
@arscan it should be good now.  It was kinda a pain to get right but I think it's working properly now with Javascript testing kicking off.

**Comment by arscan** [comment]
The travis integration looks fine and it is still working properly on my local machine.

**Pull request merged**
