### PR TITLE
Initial server history (range doppler) chart.

### PR DESCRIPTION
**Pull request by arscan**

### CODE REVIEW

**Comment by arscan** [comment]
Here's a start.  I think I'll need to check some corner cases still, but wanted to start reviewing before I sunk time into making it more robust.

Also, this might be better to check out on the DSTU2 first, so I can make a PR against that, since we have more server history for it.

**Comment by arscan** [comment]
image

**Comment by jawalonoski** [comment]
There is some amazing ruby in here...

**Comment by arscan** [comment]
image

**Comment by arscan** [comment]
I think this is good to merge now.  Just give it a shot on your local machine first to see if it works how you expect it to.  It looked ok against the dstu2 data set from production, but my mongo is acting up now that I'm trying to switch back to stu3 so I can't test it there.  But I can't imagine anything in particular could be wrong.

**Pull request merged**
