### PR TITLE
FHIR version selector for scorecard

### PR DESCRIPTION
**Pull request by dehall**
Adds a version selector to the scorecard page, to allow for selecting either DSTU2 or STU3. Default is STU3.
Note that this requires the multiversion features in the scorecard project, which is on master now but not yet released as a gem.

## Screenshot
version_selector

I'm not a UI/UX expert so I welcome any UI suggestions to make this a little nicer. (ie, using radio buttons or other mutually exclusive selector instead of a dropdown; somehow using 1 dropdown instead of 3 separate ones, 1 for each tab; etc)

### CODE REVIEW

**Comment by arscan** [comment]
I think the UI is fine -- I just updated the style so it uses bootstrap.  Have you tried updating the Gemfile.lock to point to the new version of the fhir_scorecard yet?  I gave that a shot, but ran into a versioning conflict with nokogiri, and doing a bundle update resulted in major updates in dependencies that breaks our build (namely mongoid and handlebars).  It might be a good time to modernize our dependencies, but that might take a little bit of work to get right.  Or we could just try to find the right set of gem versions that satisfy bundler without requiring any code changes.

**Comment by dehall** [comment]
How strong is the desire to maintain compatibility with Ruby 2.1? The latest commit pinned mongoid between 4.0 and 5, which produces a working combination on Ruby 2.2+ but not 2.1.

**Comment by arscan** [comment]
I'm ok upgrading to ruby 2.2, since 2.1 no longer receives security patches.  But we'll need to update production.  It looks like we use rvm in production to manage versions, and I'm pretty sure that the whole site works fine on all versions > 2.0, so hopefully that is a pretty straightforward upgrade.  Any objections @jawalonoski?

**Comment by jawalonoski** [comment]
No objections.

**Comment by arscan** [comment]
I think the build failed because handlebar_assets introduced some breaking changes starting in v0.17. I could upgrade our handlebars related code, but I'd prefer if we could find a config that allows us to stay on 0.16.  But let me know if you think upgrading to support the newer versions of that gem is the way to go and I'll take care of it.

**Comment by jawalonoski** [comment]
I say "upgrade"

**Comment by dehall** [comment]
The latest should fix the handlebars issues. I agree upgrading is the right way to go but this was a trivial code change to get it to build for now.

**Comment by arscan** [comment]
Looks good.  I've added another task to upgrade some of our dependencies.

**Pull request merged**
