### PR TITLE
url validation all set, with styling as well

### PR DESCRIPTION
**Pull request by Evana13G**

### CODE REVIEW

**Comment by arscan** [comment]
It doesn't allow things like _http://localhost:3000/_, or _http://127.0.0.1:2000/_, which is a use case that I can imagine popping up if they want to validate their server on a dev machine without registering it on _crucibleproject.org_. 

Do we care?  If the person is tech savvy they could set up their local host file to workaround this issue.

Note: it does allow arbitrary ip addresses... just not the loopback ip.

**Comment by arscan** [comment]
Besides the outstanding localhost question above, this looks fine to me.  I'm not sure that these are the best places to put the js and the css, but we can always move it as the app gets built out.

Will wait for localhost answer above and then merge

**Comment by Evana13G** [comment]
What did we decide on this @andrequina ...

**Comment by arscan** [comment]
I opened an issue in pivotal to handle the localhost case in the manner we discussed, so I believe that this part is good to merge and we can handle the localhost issue later.

https://www.pivotaltracker.com/story/show/105326178

**Pull request merged**
