### PR TITLE
Supported Formats

### PR DESCRIPTION
**Pull request by jawalonoski**
Filter tests on supported formats... e.g. don't run xml tests on json-only servers.

### CODE REVIEW

**Comment by kjmahalingam** [comment]
This looks straightforward and good to me.

EDIT: I just noticed that the check_supported_tests test has an error according to Travis. Worth looking into. If you do not notice this error on your local machine when you test, please let us know -- @arscan and I once noticed an issue where test passes were machine-dependent (it was related to a mongo gem dependency). That should have been fixed, but perhaps it wasn't.

**Comment by jawalonoski** [comment]
The test failure was due to a unit test fixture. I fixed the code to be more robust. You should consider actually testing pull requests instead of just the visual inspection.

**Comment by kjmahalingam** [comment]
I just ran the unit tests and ran some suites on a server. The tests passed and things looked good. Sorry for not being as thorough initially.

Is there a way to determine quickly whether a server is json-only, or could you point one out? I'd like to run a test on one of those servers to test this functionality specifically.

**Comment by jawalonoski** [comment]
I ran it on this toy: https://github.com/synthetichealth/candle

The way to check is `CapabilityStatement.format` should contain `json` but not `xml`

**Comment by kjmahalingam** [comment]
Confirmed that it works using candle. If @arscan sees no issue, this looks good to me.

**Pull request merged**
